name: Check Tickets
on:
  schedule:
    - cron: '*/5 * * * *' 
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v4.4.1
        with:
          product-id: 210774
          schedule-id: 100001
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }} 
          message: '@鍾宜庭 票已開放，請立即購買！' 
