name: Melon Ticket Checker

on:
  schedule:
    - cron: '*/5 * * * *' # 每 10 分鐘執行一次
  workflow_dispatch: # 手動啟動

jobs:
  check-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ticket Checker
        uses: mooyoul/melon-ticket-actions@v1
        with:
          url: ${{ secrets.MELON_URL }}       # 釋票頁面的 URL
          email: ${{ secrets.NOTIFY_EMAIL }} # 收到通知的 Email
