name: Check Tickets
on:
  schedule:
    - cron: '*/5 * * * *' 
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 210868
          schedule-id: 100002
          seat-id: 599,396
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }} # 如果不使用 Slack，可移除這一行
          message: '票已開放，請立即購買！' # 自定義通知訊息

